# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Creating complex column vectors

In [3]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)


Matrix:
 [[2 3]
 [1 4]]

Vector:
 [5 6]

Result of multiplication:
 [28 29]


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [ ]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [28]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


(array([[3.+3.j, 6.+0.j, 3.-3.j],
        [1.+1.j, 2.+5.j, 6.-2.j],
        [7.+3.j, 8.-2.j, 5.+3.j]]),
 array([[-2.-3.j, -4.+1.j, -0.-0.j],
        [-1.-1.j, -3.-3.j, -5.-0.j],
        [-4.-0.j, -6.+2.j, -1.+1.j]]),
 array([[-0.5+2.5j,  2.5+1.5j,  0. +0.j ],
        [ 0. +1.j ,  0. +3.j ,  2.5+2.5j],
        [ 2. +2.j ,  4. +2.j ,  1. +0.j ]]),
 array([[2.-3.j, 4.+1.j, 0.-0.j],
        [1.-1.j, 3.-3.j, 5.-0.j],
        [4.-0.j, 6.+2.j, 1.+1.j]]),
 array([[2.+3.j, 1.+1.j, 4.+0.j],
        [4.-1.j, 3.+3.j, 6.-2.j],
        [0.+0.j, 5.+0.j, 1.-1.j]]),
 array([[2.-3.j, 1.-1.j, 4.-0.j],
        [4.+1.j, 3.-3.j, 6.+2.j],
        [0.-0.j, 5.-0.j, 1.+1.j]]))

## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [ ]:
# Checking the dimension of matrix1
m1.shape

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [ ]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.





### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.


# Solucion del taller:

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.


In [5]:
import numpy as np

# Definir los vectores como matrices
v1 = np.array([[1+2j],
               [3-1j]])

v2 = np.array([[2-1j],
               [4+2j]])

# Sumar los vectores
resultado = v1 + v2

# Imprimir resultado
print("El resultado de la suma de los dos vectores es:")
print(resultado)

El resultado de la suma de los dos vectores es:
[[3.+1.j]
 [7.+1.j]]


# Exercise 2: Negation of a Complex Vector

Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

In [6]:
def negacion_vector_complejo(vector):
    
    return [-1 * elemento for elemento in vector]

# Vector complejo dado
v = [2 + 3j, 1 - 2j]

# Negación del vector
negacion_v = negacion_vector_complejo(v)

# Imprimir resultado
print("La negación del vector complejo es:", negacion_v)

La negación del vector complejo es: [(-2-3j), (-1+2j)]


# Exercise 3: Multiplication of a Complex Vector by a Scalar

In [7]:
def multiplicacion_vector_escalar(vector, escalar):
  
    return [elemento * escalar for elemento in vector]

# Vector complejo dado
v = [1 - 1j, 2 + 2j]

# Escalar complejo dado
escalar = 3 + 1j

# Multiplicación del vector por el escalar
resultado = multiplicacion_vector_escalar(v, escalar)

# Imprimir resultado
print("El resultado de multiplicar el vector complejo por el escalar complejo es:", resultado)

El resultado de multiplicar el vector complejo por el escalar complejo es: [(4-2j), (4+8j)]


# Exercise 4: Transpose of a Complex Vector

Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.

In [8]:
import numpy as np

def transpuesta_vector_complejo(vector):
    
    matriz_vector = np.array(vector)
    matriz_transpuesta = matriz_vector.T
    return matriz_transpuesta.tolist()

# Vector complejo dado
v = [[2 - 1j],
     [3 + 4j]]

# Transposición del vector
transpuesta_v = transpuesta_vector_complejo(v)

# Imprimir resultado
print("La traspuesta del vector complejo es:")
for fila in transpuesta_v:
    print(fila)

La transposición del vector complejo es:
[(2-1j), (3+4j)]


# Exercise 5: Conjugate of a Complex Vector

Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.

In [9]:
def conjugado_vector_complejo(vector):
   
    return [elemento.conjugate() for elemento in vector]

# Vector complejo dado
v = [1 + 1j, 2 - 3j]

# Conjugado del vector
conjugado_v = conjugado_vector_complejo(v)

# Imprimir resultado
print("El conjugado del vector complejo es:", conjugado_v)

El conjugado del vector complejo es: [(1-1j), (2+3j)]


# Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector

Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.

In [10]:
import numpy as np

def adjunto_vector_complejo(vector):
   
    matriz_vector = np.array(vector)
    transpuesta_conjugada = matriz_vector.T.conj()
    return transpuesta_conjugada.tolist()

# Vector complejo dado
v = [[1 - 2j],
     [3 + 1j]]

# Adjunto del vector
adjunto_v = adjunto_vector_complejo(v)

# Imprimir resultado
print("El adjunto del vector complejo es:")
for fila in adjunto_v:
    print(fila)

El adjunto del vector complejo es:
[(1+2j), (3-1j)]


# Exercise 7: Sum of Two Complex Matrices


Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.

In [13]:
import numpy as np

def suma_matrices_complejas(m1, m2):
    
    matriz_m1 = np.array(m1)
    matriz_m2 = np.array(m2)
    suma = matriz_m1 + matriz_m2
    return suma.tolist()

# Matrices complejas dadas
m1 = [[1 + 1j, 2 - 1j],
      [3 + 2j, 4]]

m2 = [[2 - 3j, 1],
      [1j, 2 + 2j]]

# Suma de las matrices
resultado = suma_matrices_complejas(m1, m2)

# Imprimir resultado
print("La suma de las dos matrices complejas es:")
for fila in resultado:
    print(fila)

La suma de las dos matrices complejas es:
[(3-2j), (3-1j)]
[(3+3j), (6+2j)]


# Exercise 8: Negation of a Complex Matrix


Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.

In [14]:
import numpy as np

def negacion_matriz_compleja(matriz):
   
    negacion = np.negative(matriz)
    return negacion.tolist()

# Matriz compleja dada
m = [[2 + 1j, 3],
     [1 - 1j, 2 + 2j]]

# Negación de la matriz
resultado = negacion_matriz_compleja(m)

# Imprimir resultado
print("La negación de la matriz compleja es:")
for fila in resultado:
    print(fila)

La negación de la matriz compleja es:
[(-2-1j), (-3-0j)]
[(-1+1j), (-2-2j)]


# Exercise 9: Multiplication of a Complex Matrix by a Scalar

Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.


In [15]:
import numpy as np

def multiplicacion_matriz_escalar(matriz, escalar):
 
    matriz_np = np.array(matriz)
    resultado = matriz_np * escalar
    return resultado.tolist()

# Matriz compleja dada
m = [[1 - 1j, 2],
     [3 + 1j, 4 - 2j]]

# Escalar complejo dado
escalar = 2 + 3j

# Multiplicación de la matriz por el escalar
resultado = multiplicacion_matriz_escalar(m, escalar)

# Imprimir resultado
print("El resultado de multiplicar la matriz compleja por el escalar complejo es:")
for fila in resultado:
    print(fila)

El resultado de multiplicar la matriz compleja por el escalar complejo es:
[(5+1j), (4+6j)]
[(3+11j), (14+8j)]


# Exercise 10: Conjugate of a Complex Matrix

Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.

In [16]:
def conjugado_matriz_compleja(matriz):
    
    conjugado = [[elemento.conjugate() for elemento in fila] for fila in matriz]
    return conjugado

# Matriz compleja dada
m = [[1 + 1j, 2],
     [3 - 1j, 4 + 2j]]

# Conjugado de la matriz
resultado = conjugado_matriz_compleja(m)

# Imprimir resultado
print("La conjugada de la matriz compleja es:")
for fila in resultado:
    print(fila)

La conjugada de la matriz compleja es:
[(1-1j), 2]
[(3+1j), (4-2j)]


# Exercise 11: Transpose of a Complex Matrix

Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.

In [17]:
import numpy as np

def transpuesta_matriz_compleja(matriz):
  
    matriz_np = np.array(matriz)
    transpuesta = matriz_np.T
    return transpuesta.tolist()

# Matriz compleja dada
m = [[1 - 1j, 2 + 2j],
     [3, 4 - 1j]]

# Transposición de la matriz
resultado = transpuesta_matriz_compleja(m)

# Imprimir resultado
print("La transposición de la matriz compleja es:")
for fila in resultado:
    print(fila)

La transposición de la matriz compleja es:
[(1-1j), (3+0j)]
[(2+2j), (4-1j)]


# Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix

Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.

In [18]:
import numpy as np

def adjunto_matriz_compleja(matriz):
   
    matriz_np = np.array(matriz)
    adjunto = np.conj(matriz_np.T)
    return adjunto.tolist()

# Matriz compleja dada
m = [[1 + 2j, 3 - 1j],
     [4, 5 + 1j]]

# Adjunto de la matriz
resultado = adjunto_matriz_compleja(m)

# Imprimir resultado
print("El adjunto (transpuesto conjugado) de la matriz compleja es:")
for fila in resultado:
    print(fila)

El adjunto (transpuesto conjugado) de la matriz compleja es:
[(1-2j), (4-0j)]
[(3+1j), (5-1j)]


# Exercise 13: Checking the Dimensions of a Matrix


Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.

In [26]:
def dimensiones_matriz(matriz):
   
    num_filas = len(matriz)
    num_columnas = len(matriz[0])
    return num_filas, num_columnas

# Matriz compleja dada
m = [[1 - 1j, 2],
     [3 + 2j, 4 - 1j]]

# Obtener dimensiones de la matriz
filas, columnas = dimensiones_matriz(m)

# Imprimir resultado
print("La matriz tiene", filas, "filas y", columnas, "columnas.")

La matriz tiene 2 filas y 2 columnas.


# Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector


Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.

In [30]:
import numpy as np

def multiplicar_matriz_por_vector(matriz, vector):
    
    resultado = []
    for fila in matriz:
        producto_punto = np.dot(fila, vector)
        resultado.append(producto_punto)
    return resultado

# Definir la matriz compleja
m = [[1 + 1j, 2 - 1j],
     [3, 4 + 1j]]

# Definir el vector columna complejo
v = [2 - 1j, 1 + 3j]

# Multiplicar la matriz por el vector
resultado = multiplicar_matriz_por_vector(m, v)

# Imprimir resultado
print("El resultado de multiplicar la matriz por el vector es:")
for elemento in resultado:
    print(elemento)

El resultado de multiplicar la matriz por el vector es:
(8+6j)
(7+10j)
